name = "bolao-api"
main = "server.js"
compatibility_date = "2026-06-23"

# Cloudflare D1 Database Binding
[[d1_databases]]
binding = "DB" # Available inside worker as c.env.DB
database_name = "bolao_d1"
database_id = "2d304b7d-d9d1-4f62-9ad8-786c80a575a7" # Replace with real uuid after creating it via: wrangler d1 create bolao_d1
migrations_dir = "./"

[triggers]
crons = ["*/10 * * * *"] # Executes every 10 minutes to verify predictions
